languageCode = "en-us"
baseurl = "https://xeo-it.github.io/touchboard"
title = "TouchBoard"

[Params]
	twitter = "xeo_it"
	github = "xeo-it"
	linkedin = "francescopretelli"
	cover = "images/feed.jpg"
	logo = "img/iPad.png"
	description = "Best description ever"