languageCode = "en-us"
baseurl = "https://timelabs.io/touchboard"
title = "TouchBoard"
tags = ["iOS", "touchBar", "iPad", "xamarin"]

[Params]
  twitter = "xeo_it"
  github = "xeo-it"
  linkedin = "francescopretelli"
  cover = "/images/feed.jpg"
  logo = "img/iPad.png"
  description = "Best description ever"