languageCode = "en-us"
baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "TouchBoard"

[Params]
	twitter = "xeo_it"
	github = "xeo-it"
	linkedin = "francescopretelli"
	cover = "/images/feed.jpg"
	logo = "/img/iPad.png"
	description = "Best description ever"