languageCode = "en-us"
baseurl = "https://xeo-it.github.io/touchboard"
title = "TouchBoard"

[Params]
	github = "xeo-it"
	linkedin = "francescopretelli"
	twitter = "xeo_it"
	logo = "img/iPad.png"
	description = "Visual shortcuts ninja"
	ios_id = "1187810998"